SIMULATION = 7 * 1000

NUM_INPUTS = 7
NUM_MAX_HIDDEN = 7
NUM_OUTPUTS = 2
POPULATION_SIZE = 10
GENERATIONS = 100
FPS = 60

MUTATION_RATE_ADD_NODE = 0.1
MUTATION_RATE_ADD_EDGE = 0.1
MUTATION_RATE_UPDATE_WEIGHT = 0.1
COMPATIBILITY_THRESHOLD = 6

SPECIES_SURVIVAL_RATE = 0.5
OFFSPRING_RATE = 0.5

WIN_WIDTH, WIN_HEIGHT = 1800, 1000
WIN_TITLE = "Car evolution with NEAT"
TRACK_IMAGE = "track.png"
CAR_IMAGE = "car.png"
CLICK_RADIUS = 35

CAR_MIN_SPEED = 1
CAR_MAX_SPEED = 5
